.circleci/config.yml, README.MD, src/orb.yml.hbs
- Make the build always test against dev:volatile
- Orb bug fix: Incorrect params are passed to aws-cli orb. aws-cli@0.1.4 orb actually expects the values of the aws-access-key-id, aws-secret-access-key and aws-region parameters to be actual values and not env vars. It seems the bug doesn't surface when AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION are defined as project environment variables, because the actual aws cli (not the orb) is able to read those values and configure itself.
This bug affects aws-ecs@0.0.1 and 0.0.2 and can be reproduced with the below config:
```
version: 2.1
orbs:
aws-ecr: circleci/aws-ecr@0.0.4
aws-ecs: circleci/aws-ecs@0.0.2
workflows:
build-and-deploy:
jobs:
- aws-ecr/build_and_push_image:
account-url: …
```
=> [Bug Fix] Use correct aws-cli param types

.circleci/config.yml
- refactor workflow into 2 separate workflows, so integration testing can use the just-published dev version of the orb
- add compare URL orb to only publish when relevant files / dirs are modified (a bit hacky here, b/c it's not designed to run on git tag-triggered workflows, but i think it works)
=> integration testing / auto-publishing

.circleci/config.yml, README.MD
The dev orb is now published with the alpha tag instead of volatile
=> Update config to use dev:alpha version of orb

.circleci/config.yml, tests/terraform_setup/ec2/cloudformation-templates/public-service.yml, tests/terraform_setup/ec2/terraform.tf
Update the EC2 integration test setup to use a service name that is different from the task definition family name, to facilitate testing of the service-name parameter added in version 0.0.5 (See: https://github.com/CircleCI-Public/aws-ecs-orb/pull/6)
There are no changes to the orb source, and this branch was previously used to test https://github.com/CircleCI-Public/aws-ecs-orb/pull/6, so I would like to merge in the changes so that going forward we'll continue to test the service-name parameter.
Note: The Fargate integration test setup will still use a service name that is the same as the family name, to serve as a test for that use case. And ideally we should add a regression test for testing the case of no service-name parameter being supplied.
=> Add tests for service-name parameter

README.MD, src/orb.yml.hbs
Since 0.0.10 contains a bug fix for https://github.com/CircleCI-Public/aws-ecs-orb/issues/30, it would be good to update our examples to reference that version.
=> use 0.0.10 version in examples

.circleci/config.yml, dev-docs/README.md, tests/terraform_setup/fargate_codedeploy/alb.tf, tests/terraform_setup/fargate_codedeploy/ecs.tf, tests/terraform_setup/fargate_codedeploy/network.tf, tests/terraform_setup/fargate_codedeploy/outputs.tf, tests/terraform_setup/fargate_codedeploy/roles.tf, tests/terraform_setup/fargate_codedeploy/security.tf, tests/terraform_setup/fargate_codedeploy/terraform.tf, tests/terraform_setup/fargate_codedeploy/variables.tf, tests/terraform_setup/state_init/terraform.tf
Update the integration tests to set up an environment for testing future support for blue/green deployment type (CodeDeploy) ECS services.
=> [CIRCLE-21355][CIRCLE-21358] Add blue/green deployment type ECS service setup to tests

src/orb.yml.hbs
Add Deployment Controller for Blue/Green Deployment.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-bluegreen.html
Ref: #33
I confirmed that B/G Deployment was successful using my own [orb](https://circleci.com/orbs/registry/orb/enokawa/aws-ecs).
```shell
#!/bin/bash -eo pipefail
DEPLOYMENT_CONTROLLER="$(echo CODE_DEPLOY)"
if [ "${DEPLOYMENT_CONTROLLER}" = "CODE_DEPLOY" ]; then
DEPLOYED_REVISION=$(aws deploy create-deployment \
--application-name "AppECS-sample-cluster-sample" \
--deployment-group-name "DgpECS-sample-cluster-sample" \
--revision '{"revisionType": "AppSpecContent", "appSpecContent": {"content": "{\"version\": 1, \"Resources\": [{\"TargetService\": {\"Type\": \"AWS::ECS::Service\", \"Properties\": {\"TaskDefinition\": …
```
=> Add Deployment Controller

src/orb.yml.hbs
#10 
This wraps `aws ecs run-task` with basic logic. I would love to work to get this merged (can update change / write tests etc.) I know of a couple teams that also want this functionality. 
I can also add examples.
=> feature(run-task): add run-task command

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This MR introduces issue und pull-request templates with the same format as the ones from https://github.com/CircleCI-Public/circleci-orbs/tree/staging/.github.
This increases the UX for CircleCI orbs across the different projects :)
=> feat: add issue and pull request template, based on the ones from the other CircleCI orbs

CHANGELOG.md
Add a `CHANGELOG.md` file to document orb version releases.
=> Add a changelog to document orb version releases

src/orb.yml.hbs
Update the orb description to mention Fargate, to improve discoverability of the aws-ecs orb in the orb registry for AWS Fargate users.
=> Update the orb description to mention AWS Fargate launch type support

README.MD
Changed hyperlink [orb registry listing](https://circleci.com/orbs/registry/orb/circleci/aws-ecs) from 'http' to 'https' to promote secure transport.
=> Promote HTTPS

.circleci/config.yml, src/orb.yml.hbs
- Add `overrides` parameter to `run-task` job and command to support `aws ecs run-task`'s `--overrides` option. This resolves https://github.com/CircleCI-Public/aws-ecs-orb/issues/79.
- Add integration test for `run-task` job
- Fix `run-task` example for EC2 environment
=> Enhancement: Add overrides parameter to run-task job and command

.circleci/config.yml, CHANGELOG.md, src/orb.yml.hbs
This is a fix for https://github.com/CircleCI-Public/aws-ecs-orb/issues/89.
"set -o noglob" is used to prevent unwanted expansion of asterisks present in task definitions, by the shell.
`.circleci/config.yml` has also been updated so that the integration tests include a test for the fix.
Sample test: https://circleci.com/gh/CircleCI-Public/aws-ecs-orb/2620
=> Prevent asterisk expansion when asterisk is present in task definition value [semver:patch]

.circleci/config.yml, src/orb.yml.hbs
This PR addresses #20. I like having the ability to keep my task definitions in my source code and simply updating the task definition based upon that .json.
Add the ability to update task definitions based upon a stored `.json` file
This PR was initially https://github.com/CircleCI-Public/aws-ecs-orb/pull/47 but I screwed the rebase, so here we are....
=> Add command support for --cli-input-json

.circleci/config.yml, CHANGELOG.md
Fixes the `ec2_tear-down-run-task-test` integration test job so that it tears down the task definition that was created by the integration tests (in an earlier job in the workflow), rather than an externally created one.
Example after fix: https://circleci.com/gh/CircleCI-Public/aws-ecs-orb/2737
Also updates the changelog so that it includes the most recent (unrelated to this PR) release.
=> Fix the run task integration test to tear down correct task definition

.circleci/config.yml, dev-docs/README.md, src/orb.yml.hbs
This PR solves issue #85 to make the task `update-task-definition` optional since it is already run before.
Add parameter `run-update-task-definition` to `update-service`.
Run update-task-definition only when `run-update-task-definition` parameter is set to true, defaults to false.
=> Set an optional parameter on whether to run update-task-definition in update-service.

.circleci/config.yml, src/orb.yml.hbs
- [ / ] All new jobs, commands, executors, parameters have descriptions
- [ / ] Examples have been added for any significant new features
- [ / ] README has been updated, if necessary
When using the orb in it's current state, deployment statuses of the blue-green deployment aren't reported. As a result I get no feedback as to when my new revision's deployment has failed, or succeeded in placing tasks.
A similar issue has been reported by another user, and can be seen in the issue below.
https://github.com/CircleCI-Public/aws-ecs-orb/issues/93
Adds functionality for the CircleCI parameter `verify-revision-is-deployed` for Code_deploy controllers. 
To my understanding the command above doesn't exist on the AWS CLI, but, is being emulated by waiting for the deployment.
=> Code Deploy (Blue/Green) Verify Deployment Status.

src/orb.yml.hbs
Currently, code deploy failures do not fail the job.  This adds a exit code so that the job fails properly and users are notified when a deployment isn't successful
=> [semver:patch] Add exit code 1 on failed deployment

src/commands/run-task.yml, src/jobs/run-task.yml, src/scripts/run-task.sh
Resolves https://github.com/CircleCI-Public/aws-ecs-orb/issues/121
Change the default value for the `platform-version` command/job parameter from `LATEST` to `''`, and only provide the `--platform-version` argument to the AWS CLI when `platform-version` is non-blank.
The AWS CLI docs for `--platform-version` (https://docs.aws.amazon.com/cli/latest/reference/ecs/run-task.html) state:
```
If one is not specified, the LATEST platform version is used by default
```
Hence, this PR should generally be a backwards-compatible change since the AWS CLI already uses `LATEST`  as the default when no `--platform-version` argument is provided to the CLI anyway, so not passing `--platform-version` (which will be the new orb default behavior) should have the same effect as explicitly setting …
=> [semver:minor] Always allow platform-version overrides

src/commands/update-service.yml, src/jobs/deploy-service-update.yml
Fix for https://github.com/CircleCI-Public/aws-ecs-orb/issues/120
If the `task-definition-tags` parameter is specified for the update-service command. The task definition will be updated with the tag specified.
=> [semver:minor] Add support for tagging of task-definition to update-service command

src/commands/update-service.yml
remove unnecessary quotes which create confusion around string interpolation.
These quotes make the command difficult to use, for example if you want to quote you values which may have special characters. It also throws an error if more than one key/value is used with the simple format. The json format also requires quotes around key/values which makes the removed quotes troublesome. Below are some of the manual tests I did via inlining the orb to show what I mean.
Works:
`task-definition-tags:     key=key1,value=value1`
Doesn't Work
```
task-definition-tags:     key=key1,value=value1 key=key2,value=value2
...
Error parsing parameter '--tags': Second instance of key "value" encountered for input:
key=key1,value=value1 key=key2,value=value2
^
This is often because there is a preceeding "," …
```
=> [semver:patch] fix unexpected string interpolation when using the task-definition-tags argument

.circleci/test-deploy.yml, src/jobs/deploy-service-update.yml, src/jobs/run-task.yml, src/jobs/update-task-definition-from-json.yml, src/jobs/update-task-definition.yml
Current version of the orb uses `circleci/golang` and `circleci/python` images. This PR replaces the deprecated images with the next gen `cimg` convenience images
=> chore: update executors to use cimg images

tests/terraform_setup/ec2/terraform.tf, tests/terraform_setup/fargate/terraform.tf, tests/terraform_setup/fargate_codedeploy/terraform.tf
This PR includes the following: 
- Addressing deprecation warnings
- Updating Terraform and AWS Provider versions
- Adding version constraints into `required_providers` block
=> fix: Update Terraform and AWS Provider versions

.circleci/test-deploy.yml, src/commands/run-task.yml, src/commands/update-service.yml, src/commands/update-task-definition-from-json.yml, src/commands/update-task-definition.yml, src/commands/verify-revision-is-deployed.yml, src/examples/verify-revision-deplopyment.yml, src/jobs/deploy-service-update.yml, src/jobs/run-task.yml, src/jobs/update-task-definition-from-json.yml, src/jobs/update-task-definition.yml, src/scripts/get-prev-task.sh, src/scripts/register-new-task-def.sh, src/scripts/run-task.sh, src/scripts/update-service-via-task-def.sh, src/scripts/update-task-definition-from-json.sh, src/scripts/verify-revision-is-deployed.sh
This PR adds the `profile-name`  parameter to every job and command in this orb. It enables the use of a name profile defined in the `~/.aws/credentials` file in `Linux` and `Mac` or `%USERPROFILE%\.aws\credentials` in `Windows`  with each command.
=> feat: Add `profile-name` Parameter 

src/commands/update-service.yml, src/commands/update-task-definition.yml, src/scripts/get-prev-task.sh
This PR adds the `previous-revision-number` parameter to the `update-task-definition` command. Previously, users were only able to retrieve previous tasks based families. This enables users to retrieve task definitions within the same family.
=> feat: Added previous-revision-number parameter

.circleci/test-deploy.yml, src/commands/update-service.yml, src/commands/update-task-definition.yml, src/jobs/deploy-service-update.yml, src/scripts/get-prev-task.sh, src/scripts/update-service-via-task-def.sh
This PR adds the `enable-circuit-breaker` parameter to the `update-service` command. When set to true, it enables users to  automatically roll back failing service deployments without the need to do it manually.
=> feat: Added enable-circuit-breaker parameter

src/commands/update-service.yml, src/scripts/update-bluegreen-service-via-task-def.sh
This PR applies the `enable-circuit-breaker` parameter to `AWS Code Deploy` deployments. In order to use this parameter, the `verify-revision-is-deployed` must be set to `true`. 
When `enable-circuit-breaker` is set to `true` it enables `Code Deploy` to roll back to a working state should updating the service fail.
=> feat: Added enable-circuit-breaker parameter for Code Deploy

.circleci/test-deploy.yml, src/commands/install-ecs-cli.yml, src/scripts/install-ecs-cli.sh, src/scripts/register-new-task-def.sh, src/scripts/verify-revision-is-deployed.sh
This PR adds the `install-ecs-cli` command which lets users install the `AWS ECS CLI`. Users are able to create, update and monitor clusters and tasks directly from the command line.
=> feat: implement install-ecs-cli command

src/commands/update-service.yml
Hi, this PR is about fix syntax mistake on parameter declaration.
For right now this parameter is ignored by the Circle CI and doesn't change step behavior. (https://github.com/CircleCI-Public/aws-ecs-orb/issues/133)
According to the docs the position of the parameter should be on another level: https://circleci.com/docs2/2.0/configuration-reference#ending-a-job-from-within-a-step
=> fix: Blue/Green deployment - moved timeout parameter to proper place

.circleci/test-deploy.yml, src/commands/run-task.yml, src/jobs/run-task.yml, src/scripts/run-task.sh
This PR addresses the interpolation issue for the `overrides` parameter. It enables users to use an environment variable in the  `overrides` parameter's `json` string. If your parameter contains an environment variable, `envsubst` is used to interpolate the `json` string. If the image used does not have `envsubst` installed, the script will it automatically download and install it.
=> fix: addressed override parameter interpolation 

.circleci/test-deploy.yml, src/commands/run-task.yml, src/jobs/run-task.yml, src/scripts/run-task.sh
This PR is the implementation of the `run-task-output` parameter. It enables users to specify a local `json` file to store the output logs from the `aws ecs run-task` command. The file can be used to extract information like a `task-arn`, `task-id` and more using `jq`
=> feat: implement run-task-output parameter

src/commands/deploy-ecs-scheduled-task.yml, src/jobs/update-task-definition-from-json.yml, src/jobs/update-task-definition.yml, src/scripts/deploy-ecs-scheduled-task.sh, src/scripts/update-bluegreen-service-via-task-def.sh
This PR implements the `deploy-ecs-scheduled-task` command. It enables users to deploy a valid ECS Scheduled Task Rule using the task definition  arn generated from running the `update-task-definition` command. The `update-task-definition` command must be run prior to running `deploy-ecs-scheduled-task`.
=> feat: added deploy-ecs-scheduled-task command

.circleci/test-deploy.yml, src/commands/run-task.yml, src/commands/update-service.yml, src/jobs/deploy-service-update.yml, src/scripts/run-task.sh, src/scripts/update-bluegreen-service-via-task-def.sh
This PR enables the addition of a capacity provider strategy to CodeDeploy deployments.The `codedeploy-capacity-provider-name`, `codedeploy-capacity-provider-base` and `codedeploy-capacity-provider-weight` parameters must all be provided. The AppSpec file will get updated if all three parameters are provided.
=> feat: implement capacity provider strategy

src/scripts/deploy-ecs-scheduled-task.sh
This PR applies a fix for the errors that occurs with the `deploy-ecs-scheduled-task` command.
- `bash: mktmp: command not found`
- `aws: error: the following arguments are required: --rule`
=> fix: deploy-ecs-scheduled-task errors

tests/terraform_setup/fargate/terraform.tf, tests/terraform_setup/fargate_codedeploy/terraform.tf
The latest `aws provider` version disabled automatic force delete of `aws ecr` repositories when running `terraform destroy`. This PR addresses that issue by applying `force_delete = true` to the `aws_ecr_repository` resource.
=> fix: terraform force delete

src/commands/update-service.yml
This PR passes the `profile-name` from the `update-service-command` through to the `update-task-definition` command. Without passing it through, any time a profile other than the `default` is used, the `update-task-definition` command fails.
=> fix: added profile-name parameter

src/commands/update-service.yml, src/jobs/deploy-service-update.yml, src/scripts/update-bluegreen-service-via-task-def.sh
This PR adds the `deployment-config-name` parameter to the `update-service` command and `deploy-service-update` job. It enables users to add a predefined deployment configuration when creating a Blue/Green Deployment in CodeDeploy and resolves issue #159.
=> feat: implement deployment-config-name parameter

.circleci/config.yml, .circleci/test-deploy.yml, src/@orb.yml, src/examples/deploy-ecs-scheduled-task.yml, src/examples/deploy-service-update.yml, src/examples/run-task-ec2.yml, src/examples/run-task-fargate-spot.yml, src/examples/run-task-fargate.yml, src/examples/update-service.yml, src/examples/update-task-definition-from-json.yml, src/examples/verify-revision-deplopyment.yml, src/jobs/deploy-service-update.yml, src/jobs/run-task.yml, src/jobs/update-task-definition-from-json.yml, src/jobs/update-task-definition.yml, src/scripts/run-task.sh, tests/terraform_setup/ec2/cloudformation-templates/public-service.yml, tests/terraform_setup/ec2/terraform.tf, tests/terraform_setup/fargate/terraform.tf, tests/terraform_setup/fargate_codedeploy/variables.tf, tests/test_app/Dockerfile, tests/test_app/src/main.go
This `PR` adds the `auth` parameter to all `ecs` jobs, requiring users to customize their authentication method by importing the `aws-cli` orb and using the `aws-cli/setup` command to authenticate using static AWS keys or a valid `role-arn` for OIDC.
=> feat!/auth-step-parameter

src/examples/deploy_ecs_scheduled_task.yml, src/examples/deploy_service_update.yml, src/examples/update_service.yml, src/examples/update_task_definition_from_json.yml, src/examples/verify_revision_deployment.yml
This `PR` corrects the typos found in the usage examples. It also changes all parameters to snake case
=> chore: fix parameter typos in examples

src/commands/run_task.yml, src/jobs/run_task.yml, src/scripts/run_task.sh
This is to add support for the `--enable-execute-command` option for the `run_task` command/job.  This can be useful for debugging when running tasks in a dev/staging/integration environment.  Also to make `run_task` more feature complete.
=> feat: Adding enable-execute-command option to run_task

src/commands/update_service.yml, src/examples/verify_revision_deployment.yml, src/scripts/get_prev_task.sh, src/scripts/verify_revision_is_deployed.sh
Change:
Added the `--region` option to the `aws ecs describe-task-definition` command.
Use Case:
I encountered a scenario where I, as an AWS Identity and Access Management (IAM) user, have permissions to operate in different regions. I set my AWS CLI profile region using `aws configure set default.region first-region`. Consequently, any AWS CLI operations I perform are associated with this default region.
Now, let's consider a situation where I need to update an ECS task service in a second region. The catch here is that both regions have a task definition with the same name. Consequently, the AWS CLI would typically default to using the task definition from the first region when updating.
To address this, I added the `--region` option to the `aws ecs describe-task-definition` command. By …
=> added region while describing the task definition using ecs

.circleci/test-deploy.yml, tests/terraform_setup/fargate_codedeploy/alb.tf, tests/terraform_setup/fargate_codedeploy/ecs.tf, tests/terraform_setup/fargate_codedeploy/terraform.tf, tests/terraform_setup/fargate_codedeploy/variables.tf
Previously I had removed Code Deploy tests as they were failing, and it looked like it was impossible to run. I'm fixing the tests and re adding them again to make sure we are not breaking this functionality.
=> Re add tests for code deploy

src/commands/update_service.yml
In #207 an feature was introduced to define a region for the task definition lookup. I don't know why this was a fix, because the AWS CLI should always use AWS_DEFAULT_REGION if defined as environment variable without the need to explicitly provide it as a parameter.
Thus i came across an issue where i need to define the environment variable AWS_DEFAULT_REGION for a job which points to another region for my ecr which is not in the same region as my task definition. Basically the job cannot be used for cross-region deployment this way.
As a fix, i added a new parameter "region" which can be overridden for those cases, but will default to AWS_DEFAULT_REGION environment variable to not break current usage of the update_service command.
This might be treated as minor change in sense of …
=> feat(update_service): allow to override aws region by parameter

src/jobs/deploy_service_update.yml
The PR #219 added a way to overwrite the region env, but only on the command. Deploy service update uses update_service so it should include this parameter as well.
=> Add region param to job that calls update_service

src/scripts/deploy_ecs_scheduled_task.sh
refs to https://github.com/CircleCI-Public/aws-ecs-orb/issues/222
I changed the rule to verify if the `ORB_STR_RULE_NAME` is not empty (default value). Previously it was checking if it's not set but it's being set at line 9 with an empty value:
```
ORB_STR_RULE_NAME="$(circleci env subst "${ORB_STR_RULE_NAME}")"
```
and the rule name is required to invoke the next AWS CLI commands, if it's empty it'll fail
=> fix: change `ORB_STR_RULE_NAME` validation to fail when the it's empty

.circleci/test-deploy.yml, src/commands/deploy_ecs_scheduled_task.yml, src/commands/run_task.yml, src/commands/update_service.yml, src/commands/update_task_definition.yml, src/commands/update_task_definition_from_json.yml, src/commands/verify_revision_is_deployed.yml, src/examples/deploy_ecs_scheduled_task.yml, src/examples/deploy_service_update.yml, src/examples/run_task_ec2.yml, src/examples/run_task_fargate.yml, src/examples/run_task_fargate_spot.yml, src/examples/update_service.yml, src/examples/update_task_definition_from_json.yml, src/examples/verify_revision_deployment.yml, src/jobs/deploy_service_update.yml, src/jobs/run_task.yml, src/jobs/update_task_definition.yml, src/jobs/update_task_definition_from_json.yml, src/scripts/deploy_ecs_scheduled_task.sh, src/scripts/get_prev_task.sh, src/scripts/register_new_task_def.sh, src/scripts/run_task.sh, src/scripts/update_bluegreen_service_via_task_def.sh, src/scripts/update_service_via_task_def.sh, src/scripts/update_task_definition_from_json.sh, src/scripts/verify_revision_is_deployed.sh
This changes the way region is passed to to all jobs and commands in the orb. This used to be done using the environment variable values.
The new parameter is set to used the AWS_DEFAULT_REGION env as a default when it is not set, this env was used for some other commands already.
The change should be a major version as some of the commands are just using the default region defined in the profile or the defaults environment variables, and this won't work now as the region is always explicitly set.
Also the way to pass the value is standardised to pass the value instead of the name of an environment variable. Anyway, an environment variable can be passed, but using the $ notation instead of just the name.
=> Feature: job parameter region for all the commands and jobs

.circleci/config.yml, .circleci/test-deploy.yml, src/commands/update_service.yml, src/jobs/deploy_service_update.yml, src/scripts/update_service_via_task_def.sh, tests/terraform_setup/ec2/cloudformation-templates/public-service.yml, tests/terraform_setup/ec2/terraform.tf
Add all the requirements from #228
=> Add a way to create service with update_service

.circleci/test-deploy.yml, src/commands/run_task.yml, src/examples/run_task_and_wait.yml, src/jobs/run_task.yml, src/scripts/run_task.sh
=> Enable run_task command to wait until the executions ends

src/scripts/run_task.sh
This PR exports the taskArn to bash in case you want to do something after the task ended.
For example: check the logs for errors.
=> export ORB_STR_TASK_ARN as part of $BASH_ENV
